: scldataaddr ( -- n ) 0x41200000 ;
: sdadataaddr ( -- n ) 0x41200008 ;
: sdatriaddr ( -- n ) 0x4120000C ;
: sclup ( -- ) scldataaddr 1 poke ;
: scldown ( -- ) scldataaddr 0 poke ;
: sdain ( -- ) sdatriaddr 1 poke ;
: sdaout ( -- ) sdatriaddr 0 poke ;
: sdaup ( -- ) sdadataaddr 1 poke ;
: sdadown ( -- ) sdadataaddr 0 poke ;
: sdaget ( -- n ) sdadataaddr peek ;
: sdaw ( n -- ) sdadataaddr swap poke ;
: i2cstart ( -- ) sdadown scldown ;
: i2cstop ( -- ) sclup sdaup ;
: i2cack ( -- ) sdaout sdadown sclup scldown sdaup ;
: i2cnack ( -- ) sdaout sdaup sclup scldown sdadown ;
: prepbit7 ( n -- n n ) dup 0x80 & 7 >> ;
: prepbit6 ( n -- n n ) dup 0x40 & 6 >> ;
: prepbit5 ( n -- n n ) dup 0x20 & 5 >> ;
: prepbit4 ( n -- n n ) dup 0x10 & 4 >> ;
: prepbit3 ( n -- n n ) dup 0x8 & 3 >> ;
: prepbit2 ( n -- n n ) dup 0x4 & 2 >> ;
: prepbit1 ( n -- n n ) dup 0x2 & 1 >> ;
: prepbit0 ( n -- n ) 0x1 & ;
: getacknack ( -- n ) sdain scldown sclup sdaget scldown sdaup sdaout ;
: clockbit ( n -- ) scldown sdaw sclup ;
: i2cwbyte ( n -- n ) prepbit7 clockbit prepbit6 clockbit prepbit5 clockbit prepbit4 clockbit prepbit3 clockbit prepbit2 clockbit prepbit1 clockbit prepbit0 clockbit getacknack ;
: i2crbyte ( -- n ) sdain 0 7 0 do sclup sdaget 7 i - << | scldown loop ;
: i2creceive ( n n -- ) 0x01 | i2cstart i2cwbyte 0 = if 2 do i2crbyte emit i2cack loop i2crbyte emit i2cnack fi i2cstop ;